### ISSUE TITLE
Target ja3 doesn't match real

### ISSUE THREAD

**Issue by my-0day** [an0ndev/requests-ja3#1]
Field ssl_version matches! (771 in both)
Field accepted_ciphers does not match (target [47, 53, 60, 61, 156, 157, 158, 159, 49161, 49162, 49171, 49172, 49187, 49188, 49191, 49192, 49195, 49196, 49199, 49200], real [47, 51, 53, 57, 60, 61, 103, 107, 156, 157, 158, 159, 255, 4865, 4866, 4867, 49161, 49162, 49171, 49172, 49187, 49188, 49191, 49192, 49195, 49196, 49199, 49200, 49308, 49309, 49310, 49311, 49312, 49313, 49314, 49315, 49324, 49325, 49326, 49327, 52392, 52393, 52394])
Field list_of_extensions does not match (target [0, 5, 10, 11, 13, 23, 35, 65281], real [0, 10, 11, 13, 21, 22, 23, 35, 43, 45, 49, 51])
Field elliptic_curve does not match (target [23, 24, 29], real [23, 24, 25, 29, 1035])
Field elliptic_curve_point_format does not match (target 0, real [0, 1, 2])
----------
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    Patcher.check (requests, target_ja3_str)
  File "C:\Users\tomgr\Desktop\requests-ja3\requests_ja3\patcher.py", line 45, in check
    raise Exception (basic_error_message)
Exception: real ja3 771,4866-4867-4865-49196-49200-49195-49199-52393-52392-159-158-52394-49327-49325-49326-49324-49188-49192-49187-49191-49162-49172-49161-49171-49315-49311-49314-49310-107-103-57-51-157-156-49313-49309-49312-49308-61-60-53-47-255,0-11-10-35-22-23-49-13-43-45-51-21,29-23-1035-25-24,0-1-2 does not match target ja3 771,49196-49195-49200-49199-159-158-49188-49187-49192-49191-49162-49161-49172-49171-157-156-61-60-53-47,0-5-10-11-13-35-23-65281,29-23-24,0

**Comment by an0ndev** [comment]
apologies for the lack of clarity. this project is a heavy work-in-progress and the majority of the patcher isn't even close to complete, so the core functionality doesn't work yet.

**Comment by my-0day** [comment]
Sure, no problem. Seems promising tho, nice work :)

**Comment by an0ndev** [comment]
sweet. thank you lol
